***API CALLS:***

In [2]:
import json
import requests
import pandas as pd

#You can check how many queries you already sent and how your limits are defined by calling https://api.meteomatics.com/user_stats
#The same in a machine readable format: https://api.meteomatics.com/user_stats_json

***Turbine1***

In [41]:
API_CALL = ('https://student_hulse:st7W5y9QSw@api.meteomatics.com/2023-03-17T12:00:00.000+01:00--2023-03-22T12:00:00.000+01:00:PT6H/wind_speed_100m:ms,wind_dir_100m:d/41.686371,-8.996471/json?model=mix')

response = requests.get(API_CALL)

In [42]:
# Parse the JSON response
data = json.loads(response.content)
data

{'version': '3.0',
 'user': 'student_hulse',
 'dateGenerated': '2023-03-12T15:58:28Z',
 'status': 'OK',
 'data': [{'parameter': 'wind_speed_100m:ms',
   'coordinates': [{'lat': 41.686371,
     'lon': -8.996471,
     'dates': [{'date': '2023-03-17T11:00:00Z', 'value': 10.1},
      {'date': '2023-03-17T17:00:00Z', 'value': 8.7},
      {'date': '2023-03-17T23:00:00Z', 'value': 8.3},
      {'date': '2023-03-18T05:00:00Z', 'value': 8.2},
      {'date': '2023-03-18T11:00:00Z', 'value': 13.7},
      {'date': '2023-03-18T17:00:00Z', 'value': 14.6},
      {'date': '2023-03-18T23:00:00Z', 'value': 11.4},
      {'date': '2023-03-19T05:00:00Z', 'value': 9.4},
      {'date': '2023-03-19T11:00:00Z', 'value': 7.0},
      {'date': '2023-03-19T17:00:00Z', 'value': 4.8},
      {'date': '2023-03-19T23:00:00Z', 'value': 1.6},
      {'date': '2023-03-20T05:00:00Z', 'value': 3.8},
      {'date': '2023-03-20T11:00:00Z', 'value': 7.8},
      {'date': '2023-03-20T17:00:00Z', 'value': 8.4},
      {'date': '2023-03-20T23:00:00Z', 'value': 9.4},
      {'date': '2023-03-21T05:00:00Z', 'value': 8.0},
      {'date': '2023-03-21T11:00:00Z', 'value': 5.7},
      {'date': '2023-03-21T17:00:00Z', 'value': 4.6},
      {'date': '2023-03-21T23:00:00Z', 'value': 5.1},
      {'date': '2023-03-22T05:00:00Z', 'value': 4.2},
      {'date': '2023-03-22T11:00:00Z', 'value': 3.4}]}]},
  {'parameter': 'wind_dir_100m:d',
   'coordinates': [{'lat': 41.686371,
     'lon': -8.996471,
     'dates': [{'date': '2023-03-17T11:00:00Z', 'value': 236.6},
      {'date': '2023-03-17T17:00:00Z', 'value': 239.3},
      {'date': '2023-03-17T23:00:00Z', 'value': 243.3},
      {'date': '2023-03-18T05:00:00Z', 'value': 240.1},
      {'date': '2023-03-18T11:00:00Z', 'value': 212.5},
      {'date': '2023-03-18T17:00:00Z', 'value': 315.4},
      {'date': '2023-03-18T23:00:00Z', 'value': 321.6},
      {'date': '2023-03-19T05:00:00Z', 'value': 322.9},
      {'date': '2023-03-19T11:00:00Z', 'value': 326.0},
      {'date': '2023-03-19T17:00:00Z', 'value': 327.9},
      {'date': '2023-03-19T23:00:00Z', 'value': 313.9},
      {'date': '2023-03-20T05:00:00Z', 'value': 151.8},
      {'date': '2023-03-20T11:00:00Z', 'value': 176.7},
      {'date': '2023-03-20T17:00:00Z', 'value': 229.0},
      {'date': '2023-03-20T23:00:00Z', 'value': 253.5},
      {'date': '2023-03-21T05:00:00Z', 'value': 308.2},
      {'date': '2023-03-21T11:00:00Z', 'value': 300.1},
      {'date': '2023-03-21T17:00:00Z', 'value': 272.4},
      {'date': '2023-03-21T23:00:00Z', 'value': 239.7},
      {'date': '2023-03-22T05:00:00Z', 'value': 307.7},
      {'date': '2023-03-22T11:00:00Z', 'value': 329.0}]}]}]}

In [45]:
my_data = {
    "Date": ["2023-03-17 11:00:00", "2023-03-17 17:00:00", "2023-03-17 23:00:00", "2023-03-18 05:00:00", "2023-18-10 11:00:00", "2023-03-18 17:00:00", "2023-03-18 23:00:00", "2023-03-19 05:00:00", "2023-03-19 11:00:00", "2023-03-19 17:00:00", "2023-03-19 23:00:00", "2023-03-20 05:00:00", "2023-03-20 11:00:00", "2023-03-20 17:00:00", "2023-03-20 23:00:00", "2023-03-21 05:00:00", "2023-03-21 11:00:00", "2023-03-21 17:00:00", "2023-03-21 23:00:00", "2023-03-22 05:00:00", "2023-03-22 11:00:00"],
    "wind Speed (ms)": [10.1, 8.7, 8.3, 8.2, 13.7, 14.6, 11.4, 9.4, 7.0, 4.8, 1.6, 3.8, 7.8, 8.4, 9.4, 8.0, 5.7, 4.6, 5.1, 4.2, 3.4],
    "Wind Direction (d)": [236.6, 239.3, 243.3, 240.1, 212.5, 315.4, 321.6, 322.9, 326.0, 327.9, 313.9, 151.8, 176.7, 229.0, 253.5, 308.2, 300.1, 272.4, 239.7, 307.7, 329.0]
}

In [46]:
df = pd.DataFrame(my_data)
df.rename(columns={'Date':'Time', 'wind Speed (ms)':'WindSpeed (m/s)', 'Wind Direction (d)':'Wind Direction (Â°)'}, inplace=True)
df.set_index('Time', inplace=True)
df['WindSpeed (m/s)'] = df['WindSpeed (m/s)'].astype(int)
df['Wind Direction (Â°)'] = df['Wind Direction (Â°)'].astype(int)
df

                     WindSpeed (m/s)  Wind Direction (Â°)
Time
2023-03-17 11:00:00               10                 236
2023-03-17 17:00:00                8                 239
2023-03-17 23:00:00                8                 243
2023-03-18 05:00:00                8                 240
2023-18-10 11:00:00               13                 212
2023-03-18 17:00:00               14                 315
2023-03-18 23:00:00               11                 321
2023-03-19 05:00:00                9                 322
2023-03-19 11:00:00                7                 326
2023-03-19 17:00:00                4                 327
2023-03-19 23:00:00                1                 313
2023-03-20 05:00:00                3                 151
2023-03-20 11:00:00                7                 176
2023-03-20 17:00:00                8                 229
2023-03-20 23:00:00                9                 253
2023-03-21 05:00:00                8                 308
2023-03-21 11:00:00                5                 300
2023-03-21 17:00:00                4                 272
2023-03-21 23:00:00                5                 239
2023-03-22 05:00:00                4                 307
2023-03-22 11:00:00                3                 329

In [53]:
#export so that you can add to model to get tubine predicted power:
df.to_csv('WindFloat_Atlantic_Turbine_Conditions.csv')

***Turbine2***

In [43]:
API_CALL2 = ('https://student_hulse:st7W5y9QSw@api.meteomatics.com/2023-03-17T12:00:00.000+01:00--2023-03-22T12:00:00.000+01:00:PT6H/wind_speed_100m:ms,wind_dir_100m:d/40.415956,4.220416/json?model=mix')

response2 = requests.get(API_CALL2)

In [44]:
# Parse the JSON response
data2 = json.loads(response2.content)
data2

{'version': '3.0',
 'user': 'student_hulse',
 'dateGenerated': '2023-03-12T16:07:08Z',
 'status': 'OK',
 'data': [{'parameter': 'wind_speed_100m:ms',
   'coordinates': [{'lat': 40.415956,
     'lon': 4.220416,
     'dates': [{'date': '2023-03-17T11:00:00Z', 'value': 11.6},
      {'date': '2023-03-17T17:00:00Z', 'value': 9.7},
      {'date': '2023-03-17T23:00:00Z', 'value': 5.2},
      {'date': '2023-03-18T05:00:00Z', 'value': 6.4},
      {'date': '2023-03-18T11:00:00Z', 'value': 4.3},
      {'date': '2023-03-18T17:00:00Z', 'value': 8.4},
      {'date': '2023-03-18T23:00:00Z', 'value': 8.7},
      {'date': '2023-03-19T05:00:00Z', 'value': 8.8},
      {'date': '2023-03-19T11:00:00Z', 'value': 8.4},
      {'date': '2023-03-19T17:00:00Z', 'value': 17.0},
      {'date': '2023-03-19T23:00:00Z', 'value': 17.9},
      {'date': '2023-03-20T05:00:00Z', 'value': 14.9},
      {'date': '2023-03-20T11:00:00Z', 'value': 13.8},
      {'date': '2023-03-20T17:00:00Z', 'value': 9.6},
      {'date': '2023-03-20T23:00:00Z', 'value': 5.4},
      {'date': '2023-03-21T05:00:00Z', 'value': 3.6},
      {'date': '2023-03-21T11:00:00Z', 'value': 3.5},
      {'date': '2023-03-21T17:00:00Z', 'value': 6.1},
      {'date': '2023-03-21T23:00:00Z', 'value': 2.3},
      {'date': '2023-03-22T05:00:00Z', 'value': 8.4},
      {'date': '2023-03-22T11:00:00Z', 'value': 8.7}]}]},
  {'parameter': 'wind_dir_100m:d',
   'coordinates': [{'lat': 40.415956,
     'lon': 4.220416,
     'dates': [{'date': '2023-03-17T11:00:00Z', 'value': 127.3},
      {'date': '2023-03-17T17:00:00Z', 'value': 137.1},
      {'date': '2023-03-17T23:00:00Z', 'value': 210.0},
      {'date': '2023-03-18T05:00:00Z', 'value': 259.9},
      {'date': '2023-03-18T11:00:00Z', 'value': 216.6},
      {'date': '2023-03-18T17:00:00Z', 'value': 188.3},
      {'date': '2023-03-18T23:00:00Z', 'value': 193.4},
      {'date': '2023-03-19T05:00:00Z', 'value': 224.9},
      {'date': '2023-03-19T11:00:00Z', 'value': 279.4},
      {'date': '2023-03-19T17:00:00Z', 'value': 342.0},
      {'date': '2023-03-19T23:00:00Z', 'value': 350.8},
      {'date': '2023-03-20T05:00:00Z', 'value': 0.1},
      {'date': '2023-03-20T11:00:00Z', 'value': 350.1},
      {'date': '2023-03-20T17:00:00Z', 'value': 0.8},
      {'date': '2023-03-20T23:00:00Z', 'value': 352.5},
      {'date': '2023-03-21T05:00:00Z', 'value': 311.0},
      {'date': '2023-03-21T11:00:00Z', 'value': 212.7},
      {'date': '2023-03-21T17:00:00Z', 'value': 200.6},
      {'date': '2023-03-21T23:00:00Z', 'value': 145.3},
      {'date': '2023-03-22T05:00:00Z', 'value': 178.1},
      {'date': '2023-03-22T11:00:00Z', 'value': 190.3}]}]}]}

In [47]:
my_data2 = {
    "Date": ["2023-03-17 11:00:00", "2023-03-17 17:00:00", "2023-03-17 23:00:00", "2023-03-18 05:00:00", "2023-18-10 11:00:00", "2023-03-18 17:00:00", "2023-03-18 23:00:00", "2023-03-19 05:00:00", "2023-03-19 11:00:00", "2023-03-19 17:00:00", "2023-03-19 23:00:00", "2023-03-20 05:00:00", "2023-03-20 11:00:00", "2023-03-20 17:00:00", "2023-03-20 23:00:00", "2023-03-21 05:00:00", "2023-03-21 11:00:00", "2023-03-21 17:00:00", "2023-03-21 23:00:00", "2023-03-22 05:00:00", "2023-03-22 11:00:00"],
    "wind Speed (ms)": [11.6, 9.7, 5.2, 6.4, 4.3, 8.4, 8.7, 8.8, 8.4, 17.0, 17.9, 14.9, 13.8, 9.6, 5.4, 3.6, 3.5, 6.1, 2.3, 8.4, 8.7],
    "Wind Direction (d)": [127.3, 137.1, 210.0, 259.9, 216.6, 188.3, 193.4, 224.9, 279.4, 342.0, 350.8, 0.1, 350.1, 0.8, 352.5, 311.0, 212.7, 200.6, 145.3, 178.1, 190.3]
}

In [48]:
df2 = pd.DataFrame(my_data2)
df2.rename(columns={'Date':'Time', 'wind Speed (ms)':'WindSpeed (m/s)', 'Wind Direction (d)':'Wind Direction (Â°)'}, inplace=True)
df2.set_index('Time', inplace=True)
df2['WindSpeed (m/s)'] = df2['WindSpeed (m/s)'].astype(int)
df2['Wind Direction (Â°)'] = df2['Wind Direction (Â°)'].astype(int)
df2

                     WindSpeed (m/s)  Wind Direction (Â°)
Time
2023-03-17 11:00:00               11                 127
2023-03-17 17:00:00                9                 137
2023-03-17 23:00:00                5                 210
2023-03-18 05:00:00                6                 259
2023-18-10 11:00:00                4                 216
2023-03-18 17:00:00                8                 188
2023-03-18 23:00:00                8                 193
2023-03-19 05:00:00                8                 224
2023-03-19 11:00:00                8                 279
2023-03-19 17:00:00               17                 342
2023-03-19 23:00:00               17                 350
2023-03-20 05:00:00               14                   0
2023-03-20 11:00:00               13                 350
2023-03-20 17:00:00                9                   0
2023-03-20 23:00:00                5                 352
2023-03-21 05:00:00                3                 311
2023-03-21 11:00:00                3                 212
2023-03-21 17:00:00                6                 200
2023-03-21 23:00:00                2                 145
2023-03-22 05:00:00                8                 178
2023-03-22 11:00:00                8                 190

In [54]:
#export so that you can add to model to get tubine predicted power:
df2.to_csv('Menorca_Wind_Turbine_Conditions.csv')

***Turbine3:***

In [3]:
API_CALL3 = ('https://student_hulse:st7W5y9QSw@api.meteomatics.com/2023-03-17T12:00:00.000+01:00--2023-03-22T12:00:00.000+01:00:PT6H/wind_speed_100m:ms,wind_dir_100m:d/44.585227,-7.876871/json?model=mix')

response3 = requests.get(API_CALL3)

In [4]:
# Parse the JSON response
data3 = json.loads(response3.content)
data3

{'version': '3.0',
 'user': 'student_hulse',
 'dateGenerated': '2023-03-13T11:43:12Z',
 'status': 'OK',
 'data': [{'parameter': 'wind_speed_100m:ms',
   'coordinates': [{'lat': 44.585227,
     'lon': -7.876871,
     'dates': [{'date': '2023-03-17T11:00:00Z', 'value': 13.7},
      {'date': '2023-03-17T17:00:00Z', 'value': 11.1},
      {'date': '2023-03-17T23:00:00Z', 'value': 11.5},
      {'date': '2023-03-18T05:00:00Z', 'value': 12.5},
      {'date': '2023-03-18T11:00:00Z', 'value': 11.8},
      {'date': '2023-03-18T17:00:00Z', 'value': 14.3},
      {'date': '2023-03-18T23:00:00Z', 'value': 15.9},
      {'date': '2023-03-19T05:00:00Z', 'value': 13.5},
      {'date': '2023-03-19T11:00:00Z', 'value': 13.7},
      {'date': '2023-03-19T17:00:00Z', 'value': 18.2},
      {'date': '2023-03-19T23:00:00Z', 'value': 19.1},
      {'date': '2023-03-20T05:00:00Z', 'value': 16.6},
      {'date': '2023-03-20T11:00:00Z', 'value': 15.2},
      {'date': '2023-03-20T17:00:00Z', 'value': 15.0},
      {'date': '2023-03-20T23:00:00Z', 'value': 17.2},
      {'date': '2023-03-21T05:00:00Z', 'value': 16.5},
      {'date': '2023-03-21T11:00:00Z', 'value': 14.2},
      {'date': '2023-03-21T17:00:00Z', 'value': 12.7},
      {'date': '2023-03-21T23:00:00Z', 'value': 14.1},
      {'date': '2023-03-22T05:00:00Z', 'value': 19.4},
      {'date': '2023-03-22T11:00:00Z', 'value': 15.8}]}]},
  {'parameter': 'wind_dir_100m:d',
   'coordinates': [{'lat': 44.585227,
     'lon': -7.876871,
     'dates': [{'date': '2023-03-17T11:00:00Z', 'value': 222.9},
      {'date': '2023-03-17T17:00:00Z', 'value': 253.5},
      {'date': '2023-03-17T23:00:00Z', 'value': 257.7},
      {'date': '2023-03-18T05:00:00Z', 'value': 261.4},
      {'date': '2023-03-18T11:00:00Z', 'value': 256.3},
      {'date': '2023-03-18T17:00:00Z', 'value': 226.2},
      {'date': '2023-03-18T23:00:00Z', 'value': 242.3},
      {'date': '2023-03-19T05:00:00Z', 'value': 251.1},
      {'date': '2023-03-19T11:00:00Z', 'value': 239.8},
      {'date': '2023-03-19T17:00:00Z', 'value': 230.9},
      {'date': '2023-03-19T23:00:00Z', 'value': 228.6},
      {'date': '2023-03-20T05:00:00Z', 'value': 244.4},
      {'date': '2023-03-20T11:00:00Z', 'value': 241.6},
      {'date': '2023-03-20T17:00:00Z', 'value': 238.0},
      {'date': '2023-03-20T23:00:00Z', 'value': 239.5},
      {'date': '2023-03-21T05:00:00Z', 'value': 273.6},
      {'date': '2023-03-21T11:00:00Z', 'value': 276.1},
      {'date': '2023-03-21T17:00:00Z', 'value': 272.6},
      {'date': '2023-03-21T23:00:00Z', 'value': 241.0},
      {'date': '2023-03-22T05:00:00Z', 'value': 262.2},
      {'date': '2023-03-22T11:00:00Z', 'value': 287.7}]}]}]}

In [5]:
my_data3 = {
    "Date": ["2023-03-17 11:00:00", "2023-03-17 17:00:00", "2023-03-17 23:00:00", "2023-03-18 05:00:00", "2023-18-10 11:00:00", "2023-03-18 17:00:00", "2023-03-18 23:00:00", "2023-03-19 05:00:00", "2023-03-19 11:00:00", "2023-03-19 17:00:00", "2023-03-19 23:00:00", "2023-03-20 05:00:00", "2023-03-20 11:00:00", "2023-03-20 17:00:00", "2023-03-20 23:00:00", "2023-03-21 05:00:00", "2023-03-21 11:00:00", "2023-03-21 17:00:00", "2023-03-21 23:00:00", "2023-03-22 05:00:00", "2023-03-22 11:00:00"],
    "wind Speed (ms)": [13.7, 11.1, 11.5, 12.5, 11.8, 14.3, 15.9, 13.5, 13.7, 18.2, 19.1, 16.6, 15.2, 15.0, 17.2, 16.5, 14.2, 12.7, 14.1, 19.4, 15.8],
    "Wind Direction (d)": [222.9, 253.5, 257.7, 261.4, 256.3, 226.2, 242.3, 251.1, 239.8, 230.9, 228.6, 244.4, 241.6, 238.0, 239.5, 273.6, 276.1, 272.6, 241.0, 262.2, 287.7]
}

In [6]:
df3 = pd.DataFrame(my_data3)
df3.rename(columns={'Date':'Time', 'wind Speed (ms)':'WindSpeed (m/s)', 'Wind Direction (d)':'Wind Direction (Â°)'}, inplace=True)
df3.set_index('Time', inplace=True)
df3['WindSpeed (m/s)'] = df3['WindSpeed (m/s)'].astype(int)
df3['Wind Direction (Â°)'] = df3['Wind Direction (Â°)'].astype(int)
df3

                     WindSpeed (m/s)  Wind Direction (Â°)
Time
2023-03-17 11:00:00               13                 222
2023-03-17 17:00:00               11                 253
2023-03-17 23:00:00               11                 257
2023-03-18 05:00:00               12                 261
2023-18-10 11:00:00               11                 256
2023-03-18 17:00:00               14                 226
2023-03-18 23:00:00               15                 242
2023-03-19 05:00:00               13                 251
2023-03-19 11:00:00               13                 239
2023-03-19 17:00:00               18                 230
2023-03-19 23:00:00               19                 228
2023-03-20 05:00:00               16                 244
2023-03-20 11:00:00               15                 241
2023-03-20 17:00:00               15                 238
2023-03-20 23:00:00               17                 239
2023-03-21 05:00:00               16                 273
2023-03-21 11:00:00               14                 276
2023-03-21 17:00:00               12                 272
2023-03-21 23:00:00               14                 241
2023-03-22 05:00:00               19                 262
2023-03-22 11:00:00               15                 287

In [7]:
#export so that you can add to model to get tubine predicted power:
df3.to_csv('Galicia_Wind_Turbine_Conditions.csv')